# Generated by Django 4.1.7 on 2023-05-24 12:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Folder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='フォルダ名')),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='タイトル')),
                ('author', models.CharField(max_length=255, verbose_name='著者')),
                ('progress', models.CharField(choices=[('unread', '未読'), ('reading', '読書中'), ('finished', '読了')], default='unread', max_length=10, verbose_name='読書状況')),
                ('date', models.DateField(blank=True, null=True, verbose_name='日付')),
                ('photo', models.ImageField(blank=True, upload_to='book_photos/', verbose_name='画像(任意)')),
                ('highlighted_quote', models.TextField(verbose_name='印象に残った一文')),
                ('memo', models.TextField(blank=True, verbose_name='メモ')),
                ('folder', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bookrecord.folder', verbose_name='フォルダ')),
            ],
        ),
    ]
