# Generated by Django 4.1.7 on 2023-05-24 12:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookrecord', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='folder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='bookrecord.folder', verbose_name='フォルダ'),
        ),
    ]
