# Generated by Django 4.1.7 on 2023-05-24 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookrecord', '0002_alter_book_folder'),
    ]

    operations = [
        migrations.AddField(
            model_name='folder',
            name='books',
            field=models.ManyToManyField(related_name='folders', to='bookrecord.book', verbose_name='書籍'),
        ),
    ]
