# Generated by Django 4.1.7 on 2023-05-24 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookrecord', '0003_folder_books'),
    ]

    operations = [
        migrations.AlterField(
            model_name='folder',
            name='books',
            field=models.ManyToManyField(related_name='folders', to='bookrecord.book', verbose_name='タイトル'),
        ),
    ]
