# Generated by Django 4.1.7 on 2023-05-24 13:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookrecord', '0005_remove_folder_books_remove_book_folder_book_folder'),
    ]

    operations = [
        migrations.AddField(
            model_name='folder',
            name='books',
            field=models.ManyToManyField(related_name='folders', to='bookrecord.book'),
        ),
        migrations.RemoveField(
            model_name='book',
            name='folder',
        ),
        migrations.AddField(
            model_name='book',
            name='folder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='book_records', to='bookrecord.folder', verbose_name='フォルダ'),
        ),
    ]
