# Generated by Django 4.1.7 on 2023-05-30 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookrecord', '0006_folder_books_remove_book_folder_book_folder'),
    ]

    operations = [
        migrations.RenameField(
            model_name='folder',
            old_name='name',
            new_name='folder_name',
        ),
    ]
